sudo: required

services:
        - docker

before-install :
        - docker build -t bhushanmahabal/docker-react f Dockerfile.dev . 

script:
        - docker run -e CI=true bhushanmahabal/docker-react npm run test -- --coverage
